# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7eNHC3x18dKOgk_t8g99H-GW_E2CRfq
"""

!pip install nltk scikit-learn

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

# FAQ data: apne hisaab se change kar sakta hai
faqs = {
    "What are your delivery options?": "We offer standard and express delivery across India.",
    "Do you deliver?": "Yes, we deliver to most cities. Delivery takes 3-5 days.",
    "How can I return a product?": "You can return products within 7 days of delivery.",
    "What payment methods do you accept?": "We accept UPI, cards, net banking and cash on delivery.",
    "How can I contact support?": "Email us at support@example.com or call 1800-000-000.",
}

stop_words = set(stopwords.words('english'))

def preprocess(text):
    tokens = word_tokenize(text.lower())
    return " ".join(t for t in tokens if t.isalnum() and t not in stop_words)

questions = list(faqs.keys())
answers = list(faqs.values())

vectorizer = TfidfVectorizer()
question_vectors = vectorizer.fit_transform([preprocess(q) for q in questions])

def get_answer(user_input):
    user_vec = vectorizer.transform([preprocess(user_input)])
    scores = cosine_similarity(user_vec, question_vectors)[0]
    best = scores.argmax()
    if scores[best] < 0.2:
        return "Sorry, I didn't understand that. Please try rephrasing."
    return answers[best]

print("Chatbot ready! Type 'quit' to exit.")
while True:
    user_input = input("You: ")
    if user_input.lower() == "quit":
        print("Bot: Goodbye!")
        break
    print("Bot:", get_answer(user_input))

